name: "Configure AWS credentials"

description: "Configures credentials for the selected AWS account"

inputs:
  environment_name:
    description: "The name of the environment being selected"
    required: true
  aws_region:
    description: "The AWS region to configure credentials in"
    required: true

  # Note that the roles are optional by default.
  # When using this composite action, you must pass in the role you need
  # from the `secrets` context.
  tools_account_role:
    description: "The role associated with the tools account"
    required: false
  prod_account_role:
    description: "The role associated with the prod account"
    required: false
  dev_account_role:
    description: "The role associated with the dev account"
    required: false
  test_account_role:
    description: "The role associated with the test account"
    required: false
  uat_account_role:
    description: "The role associated with the uat account"
    required: false

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials for tools account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'tools') }}
        with:
          role-to-assume: ${{ inputs.tools_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Configure AWS credentials for prod account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'prod') }}
        with:
          role-to-assume: ${{ inputs.prod_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-chaining: true

      - name: Configure AWS credentials for dev account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'dev') }}
        with:
          role-to-assume: ${{ inputs.dev_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-chaining: true

      - name: Configure AWS credentials for test account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'test') }}
        with:
          role-to-assume: ${{ inputs.test_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-chaining: true

      - name: Configure AWS credentials for uat account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'uat') }}
        with:
          role-to-assume: ${{ inputs.uat_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-chaining: true

      - name: Configure AWS credentials for uat account
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ contains(inputs.environment_name, 'train') }}
        with:
          role-to-assume: ${{ inputs.uat_account_role }}
          aws-region: ${{ inputs.AWS_REGION }}
          role-chaining: true
