version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/terraform/10-account"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/terraform/20-app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # group each package update that is common across all the lambdas together into a single PR to control the number of
  # PRs created by dependabot
  - package-ecosystem: "npm"
    directories:
      - "/src/lambda-alarm-notification"
      - "/src/lambda-api-gateway"
      - "/src/lambda-db-password-rotation"
      - "/src/lambda-front-end-revalidation"
      - "/src/lambda-producer-handler"
      - "/src/lambda-retrieve-user-permission-set"
      - "/src/legacy-dashboard-redirect-viewer-request"
      - "/src/public-api-cloud-front-viewer-request"
    schedule:
      interval: "weekly"
    groups:
      monorepo-dependencies:
        group-by: "dependency-name"
