name: "NPM Test"

description: "Runs tests in a node project"

inputs:
  function-name:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: NPM Install
      run: npm ci --no-audit --no-fund
      shell: bash
      working-directory: ./src/${{inputs.function-name}}

    - name: Unit tests
      run: npm run test:ci
      shell: bash
      working-directory: ./src/${{inputs.function-name}}

    - name: Cache unit test summary
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.function-name}}-coverage-summary
        path: ./src/${{inputs.function-name}}/coverage/coverage-summary.json

    - name: Cache unit test report
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.function-name}}-coverage-report
        path: ./src/${{inputs.function-name}}/junit.xml
