name: "Setup zsh"

description: "Setup zsh"

runs:
  using: "composite"
  steps:
    - run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update
        sudo apt-get install -y zsh
      shell: bash
