name: "Make `ENVIRONMENT_NAME` for terraform workspace name for personal dev environments"

description: "Add ENVIRONMENT_NAME env property"

inputs:
  name:
    description: "The user name on the local machine from which development/testing will be done e.g. janedoe."

runs:
  using: "composite"
  steps:
    - run: |
        source uhd.sh
        ENVIRONMENT_NAME=$(uhd terraform make-workspace-name ${{ inputs.name }})
        echo "Raw Output: '${ENVIRONMENT_NAME}'"
        CLEAN_OUTPUT=$(echo "${ENVIRONMENT_NAME}" | tr -d '\r' | xargs)
        echo "Cleaned Output: '${CLEAN_OUTPUT}'"
        echo "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}" >> $GITHUB_ENV

      shell: bash
