name: "Make `ENVIRONMENT_NAME` for terraform workspace name for personal dev environments"

description: "Add ENVIRONMENT_NAME env property"

inputs:
  name:
    description: "The user name on the local machine from which development/testing will be done e.g. janedoe."

runs:
  using: "composite"
  steps:
    - run: |
        source uhd.sh
        echo "ENVIRONMENT_NAME=`echo $(uhd terraform make-workspace-name ${{ inputs.name }})`" >> $GITHUB_ENV
      shell: bash
