name: "Setup Terraform"

description: "Setup Terraform using tfenv"

runs:
  using: "composite"
  steps:
    - id: install-tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo $HOME/.tfenv/bin >> $GITHUB_PATH
      shell: bash

    - id: install-terraform
      run: |
        tfenv install
        terraform --version
      shell: bash
