name: "Setup Terraform"

description: "Setup Terraform using tfenv"

runs:
  using: "composite"
  steps:
    - id: install-tfenv
      run: |
        rm -rf ./terraform/20-app/.terraform
        rm -rf ./terraform/10-app/.terraform
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo $HOME/.tfenv/bin >> $GITHUB_PAT
      shell: bash

    - id: install-terraform
      run: |
        rm -rf ./terraform/20-app/.terraform
        rm -rf ./terraform/10-app/.terraform
        tfenv install
        terraform --version
      shell: bash

