name: "Setup Terraform"

description: "Setup Terraform using tfenv"

runs:
  using: "composite"
  steps:
    - id: install-tfenv
      run: |
        git clone https://github.com/tfutils/tfenv.git ~/.tfenv
        echo $HOME/.tfenv/bin >> $GITHUB_PATH
      shell: bash

    - name: clear terraform cache in app layer
      run: |
        rm -rf .terraform
      shell: bash
      working-directory: ./terraform/20-app

    - name: clear terraform cache in account layer
      run: |
        rm -rf .terraform
      shell: bash
      working-directory: ./terraform/10-account

    - id: install-terraform
      run: |
        tfenv install
        terraform --version
      shell: bash

