name: "Trigger smoke test workflow"

description: "Triggers smoke test workflow in the FE repo"

inputs:
  token:
    description: "The required Github Personal Access Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Trigger deployment workflow
      run: |
        curl -L -X POST https://api.github.com/repos/UKHSA-Internal/data-dashboard-frontend/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -d '{"event_type":"trigger_smoke_tests","client_payload":{"unit":false,"integration":true}}'
      shell: bash
