runs:
  using: "composite"
  steps:
    - run: |
        source uhd.sh
        echo "==== Extracting ENVIRONMENT_NAME ===="
        echo "Raw branch name: $branch"
        
        BRANCH_NAME="${{ inputs.branch }}"
        EXTRACTED_ENVIRONMENT_NAME=$(echo "$BRANCH_NAME" | grep -oP '([^\/]+$)')
        echo "Extracted environment name: $EXTRACTED_ENVIRONMENT_NAME"

        # Ensure 'uhd-' is only prefixed once
        if [[ "$EXTRACTED_ENVIRONMENT_NAME" == uhd-* ]]; then
          FINAL_ENV_NAME="$EXTRACTED_ENVIRONMENT_NAME"
        else
          FINAL_ENV_NAME="uhd-$EXTRACTED_ENVIRONMENT_NAME"
        fi
        
        echo "Final ENVIRONMENT_NAME: $FINAL_ENV_NAME"
        
        echo "ENVIRONMENT_NAME=$FINAL_ENV_NAME" >> $GITHUB_ENV
        TARGET_ACCOUNT_NAME=$(_get_target_aws_account_name 20-app "$FINAL_ENV_NAME")
        echo "TARGET_ACCOUNT_NAME=$TARGET_ACCOUNT_NAME" >> $GITHUB_ENV

        IS_ACCOUNT_LAYER_BRANCH="false"
        if [[ "$BRANCH_NAME" =~ ^env\/(dev|test|uat|auth-dev|auth-test)\/\1$ ]]; then
          IS_ACCOUNT_LAYER_BRANCH="true"
        fi
        echo "IS_ACCOUNT_LAYER_BRANCH=$IS_ACCOUNT_LAYER_BRANCH" >> $GITHUB_ENV

        echo "==== ENVIRONMENT_NAME Set to: $FINAL_ENV_NAME ===="
        echo "TARGET_ACCOUNT_NAME: $TARGET_ACCOUNT_NAME"
        echo "IS_ACCOUNT_LAYER_BRANCH: $IS_ACCOUNT_LAYER_BRANCH"
      env:
        branch: ${{ inputs.branch }}
      shell: bash