name: "Well known environment name"

description: "Generates the well known environment name from the branch name"

inputs:
  branch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        echo "CI=true >> $GITHUB_ENV
        source uhd.sh
        echo "ENVIRONMENT_NAME=$(echo $branch | grep -P '([^\/]+$)' -o)" >> $GITHUB_ENV
        echo "TARGET_ACCOUNT_NAME=$(_get_target_aws_account_name 20-app $ENVIRONMENT_NAME)" >> $GITHUB_ENV  
        echo "IS_ACCOUNT_LAYER_BRANCH=$is_account_layer_branch" >> $GITHUB_ENV
      env:
        branch: ${{ inputs.branch }}
        is_account_layer_branch: ${{ contains(fromJSON('["env/dev/dev", "env/auth-dev/auth-dev", "env/test/test", "env/auth-test/auth-test", "env/uat/uat", "env/auth-uat/auth-uat"]'), inputs.branch) }}
      shell: bash
