name: "Well known environment name"
description: "Generates the well-known environment name from the branch name"

inputs:
  branch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        source uhd.sh
        echo "Raw branch name: ${{ inputs.branch }}"

        # Extract the environment name (last segment of the branch)
        ENVIRONMENT_NAME="${{ inputs.branch##*/ }}"

        # Determine if this is an account-layer branch
        ACCOUNT_LAYER_BRANCHES=("env/dev/dev" "env/test/test" "env/uat/uat" "env/auth-dev/auth-dev" "env/auth-test/auth-test")
        IS_ACCOUNT_LAYER_BRANCH="false"
        for branch in "${ACCOUNT_LAYER_BRANCHES[@]}"; do
          [[ "$ENVIRONMENT_NAME" == "$branch" ]] && IS_ACCOUNT_LAYER_BRANCH="true"
        done

        # Set environment variables
        echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
        echo "TARGET_ACCOUNT_NAME=$(_get_target_aws_account_name 20-app $ENVIRONMENT_NAME)" >> $GITHUB_ENV
        echo "IS_ACCOUNT_LAYER_BRANCH=$IS_ACCOUNT_LAYER_BRANCH" >> $GITHUB_ENV

        # Debug output
        echo "Extracted ENVIRONMENT_NAME: $ENVIRONMENT_NAME"
        echo "TARGET_ACCOUNT_NAME: $TARGET_ACCOUNT_NAME"
        echo "IS_ACCOUNT_LAYER_BRANCH: $IS_ACCOUNT_LAYER_BRANCH"
      shell: bash