name: "Well known environment name"

description: "Generates the well known environment name from the branch name"

inputs:
  branch:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - run: |
        source uhd.sh
        EXTRACTED_ENVIRONMENT_NAME=$(echo $branch | grep -P '([^\/]+$)' -o)

        # Remove "uhd-" if it already exists
        if [[ $EXTRACTED_ENVIRONMENT_NAME == uhd-* ]]; then
          EXTRACTED_ENVIRONMENT_NAME=${EXTRACTED_ENVIRONMENT_NAME#uhd-}
        fi

        echo "ENVIRONMENT_NAME=uhd-$EXTRACTED_ENVIRONMENT_NAME" >> $GITHUB_ENV
        echo "TARGET_ACCOUNT_NAME=$(_get_target_aws_account_name 20-app $ENVIRONMENT_NAME)" >> $GITHUB_ENV  
        echo "IS_ACCOUNT_LAYER_BRANCH=$is_account_layer_branch" >> $GITHUB_ENV
      env:
        branch: ${{ inputs.branch }}
        is_account_layer_branch: ${{ contains(fromJSON('["env/dev/dev", "env/test/test", "env/uat/uat", "env/auth-dev/auth-dev", "env/auth-test/auth-test"]'), inputs.branch) }}
      shell: bash
