name: "Run test automation"

description: "Runs the proof of concept automated test suite"

inputs:
  token:
    required: true
    type: string
  goal-id:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download Virtuoso Shell Script
      run: curl -o execute.sh https://docs.virtuoso.qa/integration/execute.sh
      shell: bash

    - name: Make Script Executable
      run: chmod +x execute.sh
      shell: bash

    - name: Execute Virtuoso Goal
      run: |
        ./execute.sh --token $token --goal_id $goal-id --app
      env:
        token: ${{ inputs.token }}
        goal-id: ${{ inputs.goal-id }}
      shell: bash
