name: "ZAP Baseline Scan"
 
on:
  push:
    branches:
      - suyash-kumar2-patch-1
 
jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
 
    steps:
       - uses: actions/checkout@v2
         with:
          ref: suyash-kumar2-patch-1
       - name: Pulling Docker Image
         run: docker pull owasp/zap2docker-stable
       - name: Launching the app
         run: docker run --rm -d -p 8080:8080 owasp/zap2docker-stable
     
       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.7.0
         with:
           target: "http://localhost:8080/?anonym=true&app=ZAP"
           fail_action: false
           command_opts: "-x ./OWASP_report.xml"
           # 14/6/23 - want to add to this .yml to extract info from the report to push to DefectDojo
