name: Production Workflow

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  fast_forward_env_branches:
    name: Fast forward env branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-zsh

      - name: Fast forward env branches
        if: false
        run: |
          - scripts/fast-forward-env-branches.sh
        shell: zsh {0}
        env:
          GH_TOKEN: ${{ github.token }}
