name: Test smoke tests

on:
  push:
    branches:
      - "main"
  repository_dispatch:
    types: [trigger-deployments]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  trigger-smoke-tests:
    name: Trigger smoke tests
    # needs: [restart_services]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: ./.github/actions/trigger-smoke-tests
        with:
          token: ${{ secrets.DEPLOYMENT_TRIGGER_TOKEN }}
