name: Well Known Environment Workflow

on:
  push:
    branches:
      - "wke/**"

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UHD_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/setup-terraform
      - uses: ./.github/actions/setup-zsh
      - uses: ./.github/actions/short-sha

      - name: Terraform plan
        run: |
          ENVIRONMENT_NAME=$(echo $GITHUB_REF_NAME | grep -P '([^\/]+$)' -o)
          source uhd.sh
          uhd terraform init:layer 20-app
          uhd terraform plan:layer 20-app $ENVIRONMENT_NAME
        shell: zsh {0}

  terraform_apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: ["terraform_plan"]
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UHD_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/setup-terraform
      - uses: ./.github/actions/setup-zsh
      - uses: ./.github/actions/short-sha

      - name: Terraform apply
        run: |
          ENVIRONMENT_NAME=$(echo $GITHUB_REF_NAME | grep -P '([^\/]+$)' -o)
          source uhd.sh
          uhd terraform init:layer 20-app
          uhd terraform apply:layer 20-app $ENVIRONMENT_NAME
        shell: zsh {0}
