name: Well Known Environment Workflow

on:
  push:
    branches:
      - "env/**"
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

env:
  AWS_REGION: "eu-west-2"
  branch: ${{ inputs.branch == '' && github.ref_name || inputs.branch }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UHD_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/setup-terraform
      - uses: ./.github/actions/setup-zsh
      - uses: ./.github/actions/well-known-environment-name
        with:
          branch: ${{ env.branch }}

      - name: Terraform plan
        run: |
          source uhd.sh
          uhd terraform init:layer 20-app
          uhd terraform plan:layer 20-app $ENVIRONMENT_NAME
        env:
          branch: ${{ env.branch }}
        shell: zsh {0}

  terraform_apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: ["terraform_plan"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UHD_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/setup-terraform
      - uses: ./.github/actions/setup-zsh
      - uses: ./.github/actions/well-known-environment-name
        with:
          branch: ${{ env.branch }}

      - name: Terraform apply
        run: |
          source uhd.sh
          uhd terraform init:layer 20-app
          uhd terraform apply:layer 20-app $ENVIRONMENT_NAME
        env:
          branch: ${{ env.branch }}
        shell: zsh {0}

  push_docker_images:
    name: Push docker images
    runs-on: ubuntu-latest
    needs: ["terraform_apply"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.UHD_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/setup-zsh
      - uses: ./.github/actions/well-known-environment-name
        with:
          branch: ${{ env.branch }}

      - name: Pull / push docker images
        run: |
          source uhd.sh
          TARGET_ACCOUNT_NAME=$(_get_target_aws_account_name 20-app $ENVIRONMENT_NAME)
          uhd docker ecr:login
          uhd docker pull
          uhd docker ecr:login $TARGET_ACCOUNT_NAME
          uhd docker push $TARGET_ACCOUNT_NAME $ENVIRONMENT_NAME
        env:
          branch: ${{ env.branch }}
        shell: zsh {0}
